// server/scripts/testRanking.js
require('dotenv').config(); // IMPORTANT: Load .env first!

const mongoose = require('mongoose');
const { getAI } = require('../services/aiTaskPrediction');
const Household = require('../model/Household');
const User = require('../model/User'); // IMPORTANT: Import User model!
const Task = require('../model/Task'); // IMPORTANT: Import Task model!

// Culori pentru terminal
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  gold: '\x1b[33m',
  silver: '\x1b[37m',
  bronze: '\x1b[38;5;208m',
  blue: '\x1b[34m',
  green: '\x1b[32m',
  cyan: '\x1b[36m',
  red: '\x1b[31m'
};

function getMedalEmoji(rank) {
  if (rank === 1) return '🥇';
  if (rank === 2) return '🥈';
  if (rank === 3) return '🥉';
  return '  ';
}

function getProgressBar(percentage, width = 30) {
  const filled = Math.round((percentage / 100) * width);
  const empty = width - filled;
  return '█'.repeat(filled) + '░'.repeat(empty);
}

function printRanking(rankingData) {
  console.log('\n');
  console.log(colors.bright + colors.cyan + '═══════════════════════════════════════════════════════════════' + colors.reset);
  console.log(colors.bright + colors.gold + '           🏆  PERFORMANCE RANKING  🏆' + colors.reset);
  console.log(colors.cyan + '═══════════════════════════════════════════════════════════════' + colors.reset);
  console.log(`${colors.blue}Household: ${colors.bright}${rankingData.householdName}${colors.reset}`);
  console.log(`${colors.blue}Generated: ${colors.reset}${new Date(rankingData.trainedOn).toLocaleString()}`);
  console.log(colors.cyan + '───────────────────────────────────────────────────────────────' + colors.reset);
  console.log('\n');

  rankingData.members.forEach((member, index) => {
    const medal = getMedalEmoji(member.rank);
    const rankColor = member.rank === 1 ? colors.gold : 
                      member.rank === 2 ? colors.silver : 
                      member.rank === 3 ? colors.bronze : colors.reset;
    
    // Header membru
    console.log(rankColor + colors.bright + '╔═════════════════════════════════════════════════════════════╗' + colors.reset);
    console.log(rankColor + `║  ${medal}  ${member.memberName.padEnd(30)} ${member.completedTasks}/${member.totalTasks} tasks (${member.completionRate}%)  ║` + colors.reset);
    console.log(rankColor + '╚═════════════════════════════════════════════════════════════╝' + colors.reset);
    
    // Progress bar
    const bar = getProgressBar(member.completionRate);
    console.log(`   ${colors.blue}${bar}${colors.reset} ${member.completionRate}%`);
    
    console.log('');
    
    // Stats
    console.log(`   ${colors.green}✓${colors.reset} AI Score:     ${colors.bright}${member.aiScore}/100${colors.reset}`);
    console.log(`   ${colors.green}✓${colors.reset} Completion:   ${member.completionRate}%`);
    console.log(`   ${colors.green}✓${colors.reset} Speed:        ${member.avgSpeed}%`);
    console.log(`   ${colors.green}✓${colors.reset} Consistency:  ${member.consistency}%`);
    
    console.log('');
    
    // Top 3 Strengths
    if (member.topStrengths && member.topStrengths.length > 0) {
      console.log(`   ${colors.gold}⭐ Top 3 Strengths:${colors.reset}`);
      console.log('');
      
      member.topStrengths.forEach((strength, i) => {
        const position = i + 1;
        console.log(`   ${colors.cyan}${position}.${colors.reset} ${colors.bright}${strength.displayName}${colors.reset}`);
        console.log(`      Score: ${strength.score}/100 • ${strength.completionRate}% done • ${strength.onTimeRate}% on-time`);
        
        if (i < member.topStrengths.length - 1) {
          console.log('');
        }
      });
    } else {
      console.log(`   ${colors.red}No category data available yet${colors.reset}`);
    }
    
    // Separator între membri
    if (index < rankingData.members.length - 1) {
      console.log('');
      console.log(colors.cyan + '───────────────────────────────────────────────────────────────' + colors.reset);
      console.log('');
    }
  });
  
  console.log('\n');
  console.log(colors.cyan + '═══════════════════════════════════════════════════════════════' + colors.reset);
  console.log(colors.green + '✅  Ranking generated by AI - Task Success Prediction' + colors.reset);
  console.log(colors.cyan + '═══════════════════════════════════════════════════════════════' + colors.reset);
  console.log('\n');
}

async function testRanking() {
  try {
    // Conectare la MongoDB
    console.log('🔌 Connecting to MongoDB...');
    console.log('📍 URI:', process.env.MONGODB_URI || 'mongodb://localhost:27017/household-app');
    
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/household-app');
    console.log('✅ Connected to MongoDB\n');
    
    // Găsește primul household disponibil
    const household = await Household.findOne().populate('members').populate('owner');
    
    if (!household) {
      console.log('❌ No household found. Please create one first.');
      console.log('💡 Make sure you are connected to the correct database.');
      console.log('   Current URI:', process.env.MONGODB_URI || 'mongodb://localhost:27017/household-app');
      process.exit(1);
    }
    
    console.log(`📋 Testing ranking for household: ${household.name}`);
    console.log(`👤 Owner: ${household.owner ? household.owner.name : 'Unknown'}`);
    console.log(`👥 Members: ${household.members.map(m => m.name).join(', ')}\n`);
    
    // Generează ranking
    const ai = getAI();
    console.log('🧠 Generating AI ranking...\n');
    
    const ranking = await ai.generateRanking(household._id);
    
    // Afișează ranking frumos
    printRanking(ranking);
    
    // Salvează și în JSON pentru debugging
    const fs = require('fs');
    fs.writeFileSync(
      'ranking-output.json', 
      JSON.stringify(ranking, null, 2)
    );
    console.log('💾 Ranking saved to ranking-output.json\n');
    
  } catch (error) {
    console.error('❌ Error:', error.message);
    console.error(error.stack);
  } finally {
    await mongoose.disconnect();
    console.log('👋 Disconnected from MongoDB');
    process.exit(0);
  }
}

// Rulează testul
if (require.main === module) {
  testRanking();
}

module.exports = { testRanking, printRanking };